

export const LOGIN_REQUEST = 'LOGIN_REQUEST',
             LOGIN_FAILURE = 'LOGIN_FAILURE',
             LOGIN_SUCCESS = 'LOGIN_SUCCESS',
             REGISTER_REQUEST = 'REGISTER_REQUEST',
             REGISTER_FAILURE = 'REGISTER_FAILURE',
             REGISTER_SUCCESS = 'REGISTER_SUCCESS',
             REGISTER_NAME_REQUEST = 'REGISTER_NAME_REQUEST';

